////
<!--
/**
  *(C) Copyright 2015-2016 Esgyn Corporation
  *
  * Confidential computer software. Valid license from Esgyn required for
  * possession, use or copying. Consistent with FAR 12.211 and 12.212,
  * Commercial Computer Software, Computer Software Documentation, and
  * Technical Data for Commercial Items are licensed to the U.S. Government
  * under vendor's standard commercial license.
  *
  */
-->
////
[[alerts]]
== Alerts
:doctype: book
:numbered:
:toc: left
:icons: font
:experimental:

DB Manager uses Bosun to monitor key system or workload metrics and generate email or http alerts based on defined rule templates. Alerts feature is only available in the EsgynDB Advanced Edition.

You can configure rule templates and notification templates in Bosun. When the rules evaluate to true, the alerts are raised. You configure your Bosun alert definitions in the *$MGBLTY_INSTALL_DIR/bosun/conf/bosun.conf* file.

Refer to the Bosun documentation at https://bosun.org/documentation.html for instructions on how to define the alert rule and notification templates.

Additionally, refer to the OpenTSDB documentation and the TCollector documentation to understand the type of metrics that are available and how to write the TSDB query expression that will be used in your Bosun alert template.

http://opentsdb.net/docs/build/html/index.html
http://opentsdb.net/docs/build/html/user_guide/utilities/tcollector.html

=== Alerts Summary
Using the Alerts page in DB Manager, you can view all active alerts for the selected time range.

The Alerts summary displays all the open and active alerts. You can narrow down the filter predicates using the *Filter* button and find alerts for specific time range and/or alert status and/or severity and/or alert text.

The Alert summary includes:

*Time*::
The time when the alert notification was generated.
*Alert Key*::
The Alert Key
*Alert*::
The subject text of the alert notification.
*Status*::
Status of the alert. Acknowledged or Un-Acknowledged.
*Severity*::
Severity State of the alert. Critical/Warning/Normal/Unknown.
*Active*::
Indicates if the alert is still active, meaning if the alert trigger condition still exists. Only inactive alerts can be closed.
*Silenced*::
Indicates if the alert has been silenced.

Click on the Alert Key hyperlink to drill-down into the details of a specific alert.

=== Alert Details
The alert detail page displays all the details of the alert. This includes the alert summary information as well as the detail information that is sent out in the notification.

If the alert has been acknowledged already by a user, it shows who acknowledged or closed the alert, when the alert was updated and the notes entered during the update.

Use the *Actions* menu to update the alert. You can acknowledge new alerts and enter a comment. For alerts that are no longer active, meaning the alert condition is no longer true, you can close the alerts.

Refer to the Bosun documentation at https://bosun.org/documentation.html for more details.
