create table JAVABENCH.H_CUSTOMER_100 
  ( C_CUSTKEY INT NO DEFAULT NOT NULL 
  , C_NAME CHAR(25) NO DEFAULT NOT NULL 
  , C_ADDRESS CHAR(40) NO DEFAULT NOT NULL 
  , C_NATIONKEY INT NO DEFAULT NOT NULL 
  , C_PHONE CHAR(15) NO DEFAULT NOT NULL 
  , C_ACCTBAL FLOAT(54) NO DEFAULT NOT NULL 
  , C_MKTSEGMENT CHAR(10) NO DEFAULT NOT NULL 
  , C_COMMENT VARCHAR(117) NO DEFAULT NOT NULL 
  , PRIMARY KEY (C_CUSTKEY ASC) ) hash partition
  ;
create table JAVABENCH.H_LINEITEM_100 ( 
    L_ORDERKEY LARGEINT NO DEFAULT NOT NULL 
  , L_PARTKEY INT NO DEFAULT NOT NULL 
  , L_SUPPKEY INT NO DEFAULT NOT NULL 
  , L_LINENUMBER INT NO DEFAULT NOT NULL 
  , L_QUANTITY FLOAT(54) NO DEFAULT NOT NULL 
  , L_EXTENDEDPRICE FLOAT(54) NO DEFAULT NOT NULL 
  , L_DISCOUNT FLOAT(54) NO DEFAULT NOT NULL 
  , L_TAX FLOAT(54) NO DEFAULT NOT NULL 
  , L_RETURNFLAG CHAR(1) NO DEFAULT NOT NULL 
  , L_LINESTATUS CHAR(1) NO DEFAULT NOT NULL 
  , L_SHIPDATE CHAR(10) NO DEFAULT NOT NULL 
  , L_COMMITDATE CHAR(10) NO DEFAULT NOT NULL 
  , L_RECEIPTDATE CHAR(10) NO DEFAULT NOT NULL 
  , L_SHIPINSTRUCT CHAR(25) NO DEFAULT NOT NULL 
  , L_SHIPMODE CHAR(10) NO DEFAULT NOT NULL 
  , L_COMMENT VARCHAR(44) NO DEFAULT NOT NULL 
  , PRIMARY KEY (L_SHIPDATE ASC, L_ORDERKEY ASC, L_LINENUMBER ASC) ) hash partition by (L_ORDERKEY);
create table JAVABENCH.H_ORDERS_100
  ( O_ORDERKEY LARGEINT NO DEFAULT NOT NULL 
  , O_CUSTKEY INT NO DEFAULT NOT NULL 
  , O_ORDERSTATUS CHAR(1) NO DEFAULT NOT NULL 
  , O_TOTALPRICE FLOAT(54) NO DEFAULT NOT NULL 
  , O_ORDERDATE CHAR(10) NO DEFAULT NOT NULL 
  , O_ORDERPRIORITY CHAR(15) NO DEFAULT NOT NULL 
  , O_CLERK CHAR(15) NO DEFAULT NOT NULL 
  , O_SHIPPRIORITY INT NO DEFAULT NOT NULL 
  , O_COMMENT VARCHAR(79) NO DEFAULT NOT NULL 
  , PRIMARY KEY (O_ORDERDATE ASC, O_ORDERKEY ASC) ) hash partition;
create table JAVABENCH.H_PART_100 ( 
    P_PARTKEY INT NO DEFAULT NOT NULL 
  , P_NAME CHAR(55) NO DEFAULT NOT NULL 
  , P_MFGR CHAR(25) NO DEFAULT NOT NULL 
  , P_BRAND CHAR(10) NO DEFAULT NOT NULL 
  , P_TYPE VARCHAR(25) NO DEFAULT NOT NULL 
  , P_SIZE INT NO DEFAULT NOT NULL 
  , P_CONTAINER CHAR(10) NO DEFAULT NOT NULL 
  , P_RETAILPRICE FLOAT(54) NO DEFAULT NOT NULL 
  , P_COMMENT VARCHAR(23) NO DEFAULT NOT NULL 
  , PRIMARY KEY (P_PARTKEY ASC) ) hash partition;
create table JAVABENCH.H_PARTSUPP_100
  ( PS_PARTKEY INT NO DEFAULT NOT NULL 
  , PS_SUPPKEY INT NO DEFAULT NOT NULL 
  , PS_AVAILQTY INT NO DEFAULT NOT NULL 
  , PS_SUPPLYCOST FLOAT(54) NO DEFAULT NOT NULL 
  , PS_COMMENT VARCHAR(199) NO DEFAULT NOT NULL 
  , PRIMARY KEY (PS_PARTKEY ASC, PS_SUPPKEY ASC) ) hash partition;
create table JAVABENCH.H_REGION_100 
  ( R_REGIONKEY INT NO DEFAULT NOT NULL 
  , R_NAME CHAR(25) NO DEFAULT NOT NULL 
  , R_COMMENT VARCHAR(152) NO DEFAULT NOT NULL 
  , PRIMARY KEY (R_REGIONKEY ASC) ) ;
create table JAVABENCH.H_SUPPLIER_100 
  ( S_SUPPKEY INT NO DEFAULT NOT NULL 
  , S_NAME CHAR(25) NO DEFAULT NOT NULL 
  , S_ADDRESS CHAR(40) NO DEFAULT NOT NULL 
  , S_NATIONKEY INT NO DEFAULT NOT NULL 
  , S_PHONE CHAR(15) NO DEFAULT NOT NULL 
  , S_ACCTBAL FLOAT(54) NO DEFAULT NOT NULL 
  , S_COMMENT VARCHAR(101) NO DEFAULT NOT NULL 
  , PRIMARY KEY (S_SUPPKEY ASC) ) hash partition;
create table JAVABENCH.H_NATION_100 
  ( N_NATIONKEY INT NO DEFAULT NOT NULL 
  , N_NAME CHAR(25) NO DEFAULT NOT NULL 
  , N_REGIONKEY INT NO DEFAULT NOT NULL 
  , N_COMMENT VARCHAR(152) NO DEFAULT NOT NULL 
  , PRIMARY KEY (N_NATIONKEY ASC) ) ;
