#!/bin/bash

declare -i lv_start
declare -i lv_end

let lv_start=$1
let lv_end=$2

let lv_first=$1

if [ $# -gt 2 ]; then
    lv_gen_insert=$3
fi

echo "sh pstat; "
echo "set schema trafodion.seabase;"
if [ $lv_gen_insert != "0" ]; then
    echo "prepare insert_stmt from insert into inventory values (?, 2, 3);"
    echo "prepare li1_stmt from insert into LI1 values (?, 100);"
    echo "prepare li2_stmt from insert into LI2 values (?, 200);"
    echo "prepare li3_stmt from insert into LI3 values (?, 300);"
    echo "prepare li1_sel  from select * from LI1 where a = ?;"
    echo "prepare li2_sel  from select * from LI2 where a = ?;"
    echo "prepare li3_sel  from select * from LI3 where a = ?;"
    echo "sh date;"
    echo
fi

while [ $lv_start -le $lv_end ]; do
      echo "begin work;"
      if [ $lv_start -eq $lv_first ]; then
	  echo "show session;"
      fi
      if [ $lv_gen_insert != "0" ]; then
	  echo "execute insert_stmt using ${lv_start};"
	  echo "execute li1_stmt using ${lv_start};"
	  echo "execute li2_stmt using ${lv_start};"
	  echo "execute li3_stmt using ${lv_start};"
	  echo "execute li1_sel using ${lv_start};"
	  echo "execute li2_sel using ${lv_start};"
	  echo "execute li3_sel using ${lv_start};"
      fi
      echo "commit work;"
      if [[ $((lv_start % 10000)) -eq 0 ]]; then
	  echo "sh pstat; "
      fi
      let lv_start=lv_start+1
done

echo "sh date;"
echo "sh pstat; "
#echo "sh sleep 60; "
