#!/bin/bash

lv_pids=`pstat | grep sqlci | cut -b14-18`
while [[ ! -z $lv_pids ]]; do
    for lv_pid in $lv_pids ; do
	let lv_num_procs=lv_num_procs+1
	echo -n "`date +%Y%m%d_%H%M` : jmap -histo:live for pid ($lv_pid): "
	$JAVA_HOME/bin/jmap -histo:live $lv_pid 
    done
    sleep $1
    lv_pids=`pstat | grep sqlci | cut -b14-18`
done



