#!/bin/bash

function getMonarchServer {
    jps | grep ServerLauncher | head -1 | cut -d' ' -f1
}

lv_pid=`getMonarchServer`
if [[ -z $lv_pid ]]; then
    echo "No Monarch Server found"
    exit 1
fi

lv_curr_time=`date +%Y%m%d_%H%M`
lv_file=monarch_server_${lv_curr_time}.${lv_pid}.jmap

echo "Executing: jmap -histo:live $lv_pid, output in the file: ${lv_file}"
$JAVA_HOME/bin/jmap -histo:live $lv_pid > ${lv_file}

