#!/bin/bash

lv_do=1
lv_jmap_sleep=30

function Exec_jmap_sqlci {
    ./jmap_sqlci ${lv_jmap_sleep} > ${lv_logdir_name}/jmap_sqlci.out
    lv_do=0
}

function Exec_jmap_hbm {
    while [ $lv_do == 1 ]; do
	./jmap_hbm | tail -1 >> ${lv_logdir_name}/jmap_hbm.out
	sleep ${lv_jmap_sleep}
    done
}

function Exec_jmap_ms {
    cd ${lv_logdir_name}
    ../jmap_ms
    cd -
}

if [ -z $EXEC_DDL ]; then
   EXEC_DDL=0
fi

if [ $EXEC_DDL -eq 1 ]; then
    sqlci -i ddl
fi

mkdir -p sql

declare -i lv_curr
declare -i lv_last
declare -i lv_startrow
declare -i lv_lastrow
declare -i lv_num_rows_per_file

let lv_curr=1
let lv_startrow=lv_curr
let lv_last=$1
let lv_num_rows_per_file=10000

if [ $# -gt 1 ]; then
    let lv_startrow=$2
fi

if [ $# -gt 2 ]; then
    let lv_num_rows_per_file=$3
fi

lv_gen_one_insert="1"
lv_gen_inserts_param="1"
if [ $# -gt 3 ]; then
    lv_gen_inserts_param=$4
    lv_gen_one_insert="0"
fi

if [ $# -gt 4 ]; then
    lv_gen_one_insert=$5
fi

echo "startrow_id: $lv_startrow"

lv_curr_time=`date +%Y%m%d_%H%M`
lv_logdir_name=test_${lv_curr_time}_${lv_last}_${lv_startrow}_${lv_num_rows_per_file}
mkdir -p ${lv_logdir_name}

echo "Generating the sql obey files"
while [ $lv_curr -le $lv_last ]; do
  let lv_lastrow=lv_startrow+lv_num_rows_per_file-1
  if [ $lv_curr -eq 1 ]; then
      lv_gen_inserts=${lv_gen_one_insert}
  else
      lv_gen_inserts=${lv_gen_inserts_param}
  fi

gen_file_prefix="data_"
./gendata ${lv_startrow} ${lv_lastrow} ${lv_gen_inserts} > ${lv_logdir_name}/${gen_file_prefix}${lv_startrow}_${lv_lastrow}.sql
  let lv_startrow=lv_startrow+lv_num_rows_per_file
  let lv_curr=lv_curr+1
done
echo "Done - Generating the sql obey files"

./jmap_hbm > ${lv_logdir_name}/jmap_hbm_full_before_begin_of_test.out

lv_message=" start running tests. Logs in the directory: ${lv_logdir_name}"
echo "`date`:${lv_message}"
date
sql_files=`ls ${lv_logdir_name}/${gen_file_prefix}*.sql`

Exec_jmap_ms

let lv_num_sql_files=0
for lv_file in ${sql_files}; do
    sqlci -i ${lv_file} > ${lv_file}.log &
    let ++lv_num_sql_files
    sleep 3
done

Exec_jmap_sqlci &
let ++lv_num_sql_files

Exec_jmap_hbm &

jobs
echo "Will wait for the job# [${lv_num_sql_files}] to finish"
wait %${lv_num_sql_files}

jobs

let ++lv_num_sql_files
kill %${lv_num_sql_files} >/dev/null 2>&1

jobs

./jmap_hbm > ${lv_logdir_name}/jmap_hbm_full_after_end_of_test.out

Exec_jmap_ms

echo "`date`: Done -${lv_message}"
lv_num_errors=`grep ' ERROR' ${lv_logdir_name}/*.log | grep -v COLD | wc -l`
echo "Number of errors: ${lv_num_errors}"

