#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#==============================================
#  EsgynDB installation script. Setup EsgynDB
#  environment, configuration of HBase with
#  Hbase-trx and co-processors need for EsgynDB, and
#  install EsgynDB. All parameters from scripts
#  use configuration file.
#==============================================

function print_usage {
cat << EOF

This script will install EsgynDB. It will create a configuration
file (if one has not been created), setup of the environment needed
for EsgynDB, configure HBase with Hbase-trx and co-processors needed,
and install a specified EsgynDB build.

Options:
    --help             Print this message and exit
    --accept_license   If provided, the user agrees to accept all the
                       provisions in the EsgynDB license.  This allows
                       for automation by skipping the display and prompt of
                       the EsgynDB license.
    --config_file      If provided, all install prompts will be
                       taken from this file and not prompted for.
EOF
}

function setModsToY {

sudo chmod 777 $TRAF_CONFIG
sed -i '/MODS_COMPLETE\=/d' $TRAF_CONFIG
echo "export MODS_COMPLETE=\"Y\"" >> $TRAF_CONFIG
sudo chmod 777 $TRAF_CONFIG
source $TRAF_CONFIG

}

function setModsToN {

sudo chmod 777 $TRAF_CONFIG
sed -i '/MODS_COMPLETE\=/d' $TRAF_CONFIG
echo "export MODS_COMPLETE=\"N\"" >> $TRAF_CONFIG
sudo chmod 777 $TRAF_CONFIG
source $TRAF_CONFIG

}



#==============================================
#Parse input
USER_CONFIG=""
ACCEPT_LICENSE="N"
RUN_SCANNER="N"
export TRAF_CONFIG="/etc/trafodion/trafodion_config"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)
            print_usage
            exit -1
            ;;
        --accept_license)
            ACCEPT_LICENSE="Y"
            ;;
        --config_file)
            if [[ -z "$2" ]]; then
                echo "***ERROR: No value passed to param $1."
                print_usage
                exit -1
            fi
            USER_CONFIG=$2
            if [ -f $USER_CONFIG ]; then
               source $USER_CONFIG
            else
               echo "***ERROR: configuration file $USER_CONFIG does not exist"
               exit -1
            fi
            shift
            ;;
        *)
            echo "***ERROR: unknown parameter '$1'"
            print_usage
            exit -1
    esac
    shift
done


#==============================================
#Set start all flag to N
echo
echo "******************************"
echo " EsgynDB INSTALLATION START"
echo "******************************"


if [[ -f $USER_CONFIG ]]; then
   ./trafodion_install --accept_license --config_file $USER_CONFIG --no_start
else
   ./trafodion_install --no_start
fi

setModsToY

if [[ $? -eq 0 ]]; then
   source /etc/trafodion/trafodion_config
   ./esgyn_dbManager_setup | tee -a $INSTALL_LOG
   sudo su $TRAF_USER --command "$TRAF_WORKDIR/installer/traf_start" 2>&1 | tee -a $INSTALL_LOG
   ./esgyn_dbManager_start | tee -a $INSTALL_LOG
fi

setModsToN
