#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

TRAF_CONFIG=/etc/trafodion/trafodion_config
source $TRAF_CONFIG


function restartMgblty {
 
source $TRAF_CONFIG
echo "Some of the dependent processes like mxosrvr may not be fully up when manageability processes were first started." >> $INSTALL_LOG
echo "Stopping the manageability processes. They will be automatically restarted by \$CMON and \$NMON, allowing them to connect with dependent processes." >> $INSTALL_LOG
$SQ_ROOT/sql/scripts/mgblty_stop >> $INSTALL_LOG
 
}
 
 
#Main
echo "***INFO: Restarting EsgynDB Manageability Components" >> $INSTALL_LOG

restartMgblty


