#!/bin/bash

# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#  Script that prompts user for all user input needed for the
#  trafodion_config file. This script will be called from
#  traf_config_setup and will prompt for user needed prompts. 


export TRAF_CONFIG="/etc/trafodion/trafodion_config"

function checkDBAdminUser {

if [[ "$LDAP_SECURITY" == "Y" ]]; then
   if [ -z $DB_ADMIN_NAME ]; then
      echo "***ERROR: DB_ADMIN_NAME variable not set in config file."
      echo "***ERROR: DB_ADMIN_PASSWORD variable will need to be set as well."
      exit -1
   fi

  if [[ "$DB_ADMIN_NAME" == "$DB_ROOT_NAME" ]]; then
    echo "***ERROR: DB admin LDAP user cannot be the same as the DB root LDAP user."
    exit -1
  fi

fi

}

function checkDBAdminPass {

if [[ "$LDAP_SECURITY" == "Y" ]]; then
   if [ -z $DB_ADMIN_PASSWORD ]; then
      echo "***ERROR: DB_ADMIN_PASSWORD variable not set in config file."
      exit -1
   fi
fi

}


#Main

source $TRAF_CONFIG

checkDBAdminUser
checkDBAdminPass
