#!/bin/bash

# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#  Script that prompts user for all user input needed for the
#  trafodion_config file. This script will be called from
#  traf_config_setup and will prompt for user needed prompts. 


export TRAF_CONFIG="/etc/trafodion/trafodion_config"
export DB_ADMIN_USER="DB__ADMINUSER"
export DB_ADMIN_PASSWORD="traf123"

function getDBAdminUser {

#Hadoop user name
sudo chmod 777 $TRAF_CONFIG  
echo -n "Enter DB Admin username, default is [$DB_ADMIN_USER]: "
read answer

if [ -z $answer ]; then 
   echo "export DB_ADMIN_USER=\"$DB_ADMIN_USER\"" >> $TRAF_CONFIG
else
    
   echo "export DB_ADMIN_USER=\"$answer\"" >> $TRAF_CONFIG
fi

#==============================================
#Hadoop Password
sudo chmod 777 $TRAF_CONFIG
echo -n "Enter DB Admin password, default is [$DB_ADMIN_PASSWORD]: "
read answer

if [ -z $answer ]; then
   echo "export DB_ADMIN_PASSWORD=\"$DB_ADMIN_PASSWORD\"" >> $TRAF_CONFIG
else
   echo "export DB_ADMIN_PASSWORD=\"$answer\"" >> $TRAF_CONFIG
fi

}


#Main

source $TRAF_CONFIG

getDBAdminUser
