#!/bin/bash

if [ -z $JAVA_HOME ]; then
    echo "The environment variable $JAVA_HOME has not been set"
    echo "Please ensure $MY_SQROOT/sqenv.sh has been sourced."
    echo
    exit 1;
fi

mkdir -p $MY_SQROOT/logs
lv_stderr_file="$MY_SQROOT/logs/hbstatus.err"
echo "Stderr being written to the file: ${lv_stderr_file}"
$JAVA_HOME/bin/java org.trafodion.dtm.hbstatus $* 2>${lv_stderr_file}

