#!/bin/bash

cd $MY_SQROOT/tools/check_hbase_available
echo "Building some utility Java programs."
. ./build 2>/dev/null
$JAVA_HOME/bin/java CheckHBase | grep -v "Checking" | grep "HBase is available"
lv_status=$?
if [[ $lv_status == 0 ]]; then
   echo "HBase Master is available."
else
   echo "HBase Master is not accessible. Please check the HBase logs" 
   exit 1
fi

echo
echo "Checking if HBase is functional..."
echo

swhbase <<EOF > hbase_status_detailed.out
status 'detailed'
EOF

declare -i lv_num_live_rs 
lv_num_live_rs=`cat hbase_status_detailed.out | grep live | cut -d' ' -f1`
echo "Number of live region servers: ${lv_num_live_rs}"
if [ ${lv_num_live_rs} '>' '0' ] ; then
   echo
   echo "Checking if regions are online" 
else
   echo "There does not seem to be any live region server available"
   echo "Please check the HBase logs or the management interfaces"
   exit 1
fi

declare -i lv_num_online_regions
lv_num_online_regions=`cat hbase_status_detailed.out | grep -o "numberOfOnlineRegions=[0-9]*" | cut -d= -f2`
echo "The number of online regions: ${lv_num_online_regions}"
if [ ${lv_num_online_regions} -lt 2 ]; then
    echo "Error: There does not seem to be enough online region. Exitting..."
    exit 1
fi

exit 0
