#!/bin/bash

#
# This script cleans up the HBase env 
# that was setup by install_local_hadoop.
# It requires Hadoop to be up.
#
# - kills the HBase Master process (if it exists)
# - deletes the HBase log files
# - deletes the HDFS directory /hbase
#
# After running this script:
# - swstarthbase
# - sqstart
# - initialize trafodion
#

 
function getMyNameNode {
    jps | grep -w NameNode | cut -d' ' -f1
}

function getMyDataNode {
    jps | grep -w DataNode | cut -d' ' -f1
}

function getMyHMaster {
    jps | grep HMaster | cut -d' ' -f1
}

function killMyHMaster {

    lv_hbpid=`getMyHMaster`
    if [ ! -z ${lv_hbpid} ]; then
	echo "Killing HMaster pid: ${lv_hbpid}"
	kill -9 ${lv_hbpid}
    else
	echo "There's no HMaster process to kill"
    fi

}

lv_nnpid=`getMyNameNode`
if [ -z ${lv_nnpid} ]; then
    echo "NameNode is not up - please run swstarthadoop to start it or check the Hadoop logs - exitting..."
    exit 1
fi
echo "NameNode pid: ${lv_nnpid}"

lv_dnpid=`getMyDataNode`
if [ -z ${lv_dnpid} ]; then
    echo "DataNode is not up - please run swstarthadoop to start it or check the Hadoop logs - exitting..."
    exit 1
fi
echo "DataNode pid: ${lv_dnpid}"

# stop / kill the HMaster process
killMyHMaster

# delete the zookeeper info
lv_zk_dir="${MY_SQROOT}/sql/local_hadoop/hdfs:"
echo "Deleting the zookeeper directory: ${lv_zk_dir}"
rm -rf ${lv_zk_dir}

#delete the logs
echo "Deleting HBase logs in: ${MY_SQROOT}/sql/local_hadoop/hbase/logs"
if [ ! -z ${MY_SQROOT} ]; then
    rm -rf ${MY_SQROOT}/sql/local_hadoop/hbase/logs/*.log
    rm -rf ${MY_SQROOT}/sql/local_hadoop/hbase/logs/*log.[0-9]*
    rm -rf ${MY_SQROOT}/sql/local_hadoop/hbase/logs/*.out
    rm -rf ${MY_SQROOT}/sql/local_hadoop/hbase/logs/*.out.[0-9]*
fi

# delete the HBase table data from HDFS
echo "Deleting the HBase data directory (hdfs) /hbase"
swhdfs dfs -rm -f -r -skipTrash /hbase

