#!/bin/bash

# @@@ START COPYRIGHT @@@ 
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

#### Script to install and configure Manageability tools
#### OpenTSDB, TCollector and Bosun...

# Location of manageability folder
export MGBLTY_TOOLSDIR=$MY_SQROOT/../../mgblty
if [[ ! -d $MGBLTY_TOOLSDIR ]]; then
    mkdir -p $MGBLTY_TOOLSDIR
fi

# Default location of OpenTSDB, TCollector, Bosun folders 
OPENTSDB_DIR=$MGBLTY_TOOLSDIR/opentsdb
TCOLLECTOR_DIR=$MGBLTY_TOOLSDIR/tcollector
BOSUN_DIR=$MGBLTY_TOOLSDIR/bosun
JYTHON_DIR=$MGBLTY_TOOLSDIR/jython2.7.0

# Location of manageability log file
MY_SW_ROOT=$MY_SQROOT/sql/local_hadoop
MGBLTY_LOG=$MY_SW_ROOT/log/install_mgblty_$(date +%F_%T).log

# Location of temporary download folder
MGBLTY_DOWNLOAD_DIR=$MY_SQROOT/../dbmgr/mgblty_download

if [ -d $OPENTSDB_DIR ] && [ -d $TCOLLECTOR_DIR ] &&
        [ -d $BOSUN_DIR ] && [ -d $JYTHON_DIR ]; then
    echo "Manageability tools (tcollector, opentsdb, bosun and jython) already exists.." | tee -a ${MGBLTY_LOG}
else
    mkdir -p $MGBLTY_DOWNLOAD_DIR
    cd $MGBLTY_DOWNLOAD_DIR
    echo
    if [[ -f $MGBLTY_DOWNLOAD_DIR/bosun-linux-amd64 ]]; then
   	echo "Bosun download file already exists, skipping download of bosun " | tee -a ${MGBLTY_LOG}
    else
        echo "Downloading and installing bosun"| tee -a ${MGBLTY_LOG}
        wget https://github.com/bosun-monitor/bosun/releases/download/0.4.0/bosun-linux-amd64
        wget https://github.com/bosun-monitor/bosun/releases/download/0.4.0/scollector-linux-amd64
        wget https://raw.githubusercontent.com/bosun-monitor/bosun/master/LICENSE
    fi
    if [[ ! -d $BOSUN_DIR ]]; then
       echo "Copying bosun files..."
       mkdir -p $BOSUN_DIR/bin
       cp -p bosun-linux-amd64 $BOSUN_DIR/bin
       cp -p scollector-linux-amd64 $BOSUN_DIR/bin
       cp -p LICENSE $BOSUN_DIR
       echo "Completed setup of Bosun" | tee -a ${MGBLTY_LOG}
    else
       echo "Bosun files already exist " |tee -a ${MGBLTY_LOG}
    fi
    echo
    cd $MGBLTY_DOWNLOAD_DIR
    if [[ -d $MGBLTY_DOWNLOAD_DIR/tcollector ]]; then
      echo "Tcollector download files already exists, skipping tcollector download" | tee -a ${MGBLTY_LOG}
    else
       echo "Downloading and installing tcollector"| tee -a ${MGBLTY_LOG}
       git clone git://github.com/OpenTSDB/tcollector.git
    fi
    if [[ ! -d $TCOLLECTOR_DIR ]]; then
       echo "Copying tcollector files..."
       mkdir -p $TCOLLECTOR_DIR
       cp -p tcollector/*.py $TCOLLECTOR_DIR
       cp -p tcollector/startstop $TCOLLECTOR_DIR
       cp -rp tcollector/collectors $TCOLLECTOR_DIR
       cp -rp tcollector/stumbleupon $TCOLLECTOR_DIR
       cp -rp tcollector/COPYING $TCOLLECTOR_DIR
       echo "Completed set up of Tcollector" | tee -a ${MGBLTY_LOG}
    else
       echo "Tcollector files already exist " |tee -a ${MGBLTY_LOG}
    fi
    echo
    cd $MGBLTY_DOWNLOAD_DIR
    OPENTSDB_TMP_DIR=$MGBLTY_DOWNLOAD_DIR/myinst-${USER}
    if [[ -d $MGBLTY_DOWNLOAD_DIR/opentsdb ]]; then
       echo "opentsdb download files already exists, skipping opentsdb download" | tee -a ${MGBLTY_LOG}
    else
       echo "Downloading and installing openTSDB"| tee -a ${MGBLTY_LOG}
       git clone git://github.com/OpenTSDB/opentsdb.git
       cd opentsdb && ./bootstrap
       mkdir build
       cd build
       ../configure --prefix=$OPENTSDB_TMP_DIR "$@"  
       /bin/sh $PWD 
       unset CLASSPATH
       make 
       cd ../../
    fi
    if [[ ! -d $OPENTSDB_DIR ]]; then
       cd opentsdb/build
       make install
       cp -rp gwt/queryui/*  $OPENTSDB_TMP_DIR/share/opentsdb/static
       cp -rp $OPENTSDB_TMP_DIR/bin/tsdb $OPENTSDB_TMP_DIR/share/opentsdb/bin
       cd $OPENTSDB_TMP_DIR/share/opentsdb/bin
       mv -f tsdb tsdb-orig 
       sed -e "s@pkgdatadir='$OPENTSDB_TMP_DIR/share/opentsdb'@pkgdatadir=\$MGBLTY_INSTALL_DIR/opentsdb@" -e "s@configdir='$OPENTSDB_TMP_DIR/share/opentsdb/etc/opentsdb'@configdir=\$MGBLTY_INSTALL_DIR/opentsdb/etc/opentsdb@" tsdb-orig > tsdb
       chmod +x tsdb
       rm -f tsdb-orig
       cd $MY_SQROOT/sql/scripts
       cp -rp $OPENTSDB_TMP_DIR/share/opentsdb $MGBLTY_TOOLSDIR
       cd $MGBLTY_DOWNLOAD_DIR/opentsdb
       cp -rp COPYING $OPENTSDB_DIR
       echo "Completed set up of OpenTSDB " | tee -a ${MGBLTY_LOG}
       rm -rf $OPENTSDB_TMP_DIR 
    else
       echo "openTSDB files already exist " |tee -a ${MGBLTY_LOG}
    fi
    echo
    cd $MGBLTY_DOWNLOAD_DIR
    if [[ -f $MGBLTY_DOWNLOAD_DIR/jython_installer.jar ]]; then
       echo "Jython installer jar already exists, skipping jython download step" | tee -a ${MGBLTY_LOG}
    else
       echo "Downloading and installing Jython"| tee -a ${MGBLTY_LOG}
       wget http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar -O jython_installer.jar
    fi
    if [[ ! -d $JYTHON_DIR ]]; then
       echo "Installing jython files..."
       mkdir -p $JYTHON_DIR
       /bin/sh $PWD
       unset PATH
       $JAVA_HOME/bin/java -jar jython_installer.jar -s -d $JYTHON_DIR -t minimum 2>/dev/null
       echo "Completed setup of Jython" 
    else
       echo "Jython files already exist " |tee -a ${MGBLTY_LOG}
    fi
    echo
    cds
    echo "Successfully installed manageability tools"
    echo
    exit 0
fi
