#!/bin/bash

#All rights reserved by Esgyn Corporation 2015 
#this script will check if current installation has a valid license or not
silent=0
if [[ $1 = "-s" ]];then
  silent=1
fi

encstring=""

if [[ -f ./esgyn.el ]]; then
  encstring=`cat ./esgyn.el`
elif [[ -f ../esgyn.el ]]; then
  encstring=`cat ../esgyn.el`
elif [[ -f $MY_SQROOT/esgyn.el ]]; then
  encstring=`cat  $MY_SQROOT/esgyn.el`
elif [[ -f $HOME/esgyn.el ]]; then
  encstring=`cat  $HOME/esgyn.el`
fi

if [[ $encstring = "" ]]; then
  #print warning and continue
  echo "***Your license to use the EsgynDB Enterprise Edition is either unavailable or the file is corrupt."
  exit 1
fi

#now we have the enc string 
#decode the enc string to check
#for this release, we only check the node number
if [[ -f $1/traf_sqconfig ]]; then
  #this is invoked from installer  
  nodenumber=`$1/decoder -n -s $encstring`
else
  nodenumber=`decoder -n -s $encstring`
fi

#get the real nodenumber from $NODE_LIST
node_count=$(echo $NODE_LIST | wc -w)

if [[ $node_count -gt $nodenumber ]]; then
  echo "***Your license for use of EsgynDB Enterprise Edition only supports " $nodenumber " hosts."
  exit 1
fi

echo ""
exit 0

