#!/bin/bash
# @@@ START COPYRIGHT @@@ 
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

jpscmd=$JAVA_HOME/bin/jps
echo 

echo "Status of OpenTSD..."
$MGBLTY_INSTALL_DIR/opentsdb/bin/tsd.sh status

#Check for the number of TSD process
if [ -e $SQ_PDSH ]; then
   actual_tsd_cnt=`$SQ_PDSH $MY_NODES $jpscmd |grep TSDMain |wc -l`
else
   actual_tsd_cnt=`$jpscmd |grep TSDMain |wc -l`
fi
echo "Total count of TSD process: $actual_tsd_cnt"

echo 
echo "Status of Tcollector..."
$MGBLTY_INSTALL_DIR/tcollector/startstop status
#Check for the number of Tcollector process
if [ -e $SQ_PDSH ]; then
   actual_tcollector_cnt=`$SQ_PDSH $MY_NODES ps -ef |grep [t]collector.py |grep $USER |wc -l`
else
   actual_tcollector_cnt=`ps -ef |grep [t]collector.py |grep $USER |wc -l`
fi
echo "Total count of Tcollectors: " $actual_tcollector_cnt
echo 

echo "Status of DBMgr..."
$DBMGR_INSTALL_DIR/bin/dbmgr.sh status
echo 

# For future use
#$MGBLTY_DIR/bosun/bin/runbosun.sh status
