#!/bin/bash
# @@@ START COPYRIGHT @@@ 
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

echo
if [ -e $SQ_PDSH ]; then
   L_PDSH="$PDSH $MY_NODES $PDSH_SSH_CMD"
else
   L_PDSH=
fi
echo "Stopping OpenTSD..."
$L_PDSH $MGBLTY_INSTALL_DIR/opentsdb/bin/tsd.sh stop
echo
echo "Stopping Tcollector..."
$L_PDSH $MGBLTY_INSTALL_DIR/tcollector/startstop stop
echo
echo "Stopping DBMgr..."
$DBMGR_INSTALL_DIR/bin/dbmgr.sh stop
echo

echo "Stopping Bosun..."
$MGBLTY_INSTALL_DIR/bosun/bin/runbosun.sh stop
