#!/bin/bash
# @@@ START COPYRIGHT @@@ 
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

export PATH=$MGBLTY_INSTALL_DIR/jython2.7.0/bin:$PATH
#Check if Trafodion is up and running
trafcheck
tf_stat=$?
if ( [ $tf_stat == 0 ]  || [ $tf_stat == 1 ] ); then
	echo
	echo "Starting OpenTSD..."
	$MGBLTY_INSTALL_DIR/opentsdb/bin/tsd.sh start
	echo
	echo "Starting Tcollector..."
	$MGBLTY_INSTALL_DIR/tcollector/startstop start
	echo
	echo "Starting DBMgr..."
	$DBMGR_INSTALL_DIR/bin/dbmgr.sh start
	echo
else
	echo "Trafodion is partially up or not started..."
        exit 1
fi
