#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#

if [[ -z $MY_SQROOT ]]; then
    echo "The environment variable MY_SQROOT is not present."
    echo "Looks like the Trafodion environment has not been configured. Exitting..."
    exit 5;
fi

if [[ -z $SQSCRIPTS_DIR ]]; then
    SQSCRIPTS_DIR=$MY_SQROOT/sql/scripts
fi
SQCONFIGDB_FILE="$SQSCRIPTS_DIR/sqconfig.db"
if [[ ! -e ${SQCONFIGDB_FILE} ]]; then
    echo "Cannot find the Trafodion configuration DB file ${SQCONFIGDB_FILE}"
    echo "Please execute sqgen to generate this file."
    exit 5;
fi

grep_out=`pstat | grep "monitor COLD" | grep -v mpirun`
if [[ $? == '0' ]]; then
   echo "The Trafodion monitor seems to be running on this node - let's check the status..."
   sqcheck
   exit $?
else
   echo "Trafodion is not running on the current node: `hostname`"
fi

if [[ ! -z ${SQ_VIRTUAL_NODES} ]]; then
    # Running in a single node environment
    echo "Tradfodion has been configured to run on a single virtual node environment."
    exit 1
fi

echo
echo "Trafodion has been configured to run on these nodes:"
sqlite3 ${SQCONFIGDB_FILE} <<EOF
select nodeName from pnode;
.quit
EOF

echo 
echo "Let's check if Trafodion is running on other nodes"

grep_out=`cstat | grep "monitor COLD" | grep -v mpirun | cut -d: -f1`
lv_ret=$?
if [[ $lv_ret == 0 ]]; then
    echo
    echo "Trafodion seems to be running on these nodes:"
    echo "$grep_out"
    for lv_node in $grep_out; do
	echo
        echo "Executing sqcheck on node: $lv_node"
        echo "ssh $lv_node sqcheck"
        ssh $lv_node sqcheck
        exit $?
    done
else
    echo "Trafodion is currently down."
    exit 1;
fi
