#!/bin/bash

# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@


TRAF_CONFIG=/etc/trafodion/trafodion_config
source $TRAF_CONFIG
#============================================

ssh localhost "cd $SQ_ROOT/sql/scripts;  echo \"initialize Trafodion;\" | sqlci" | tee -a $SQ_ROOT/initializeErrors.txt

$SQ_ROOT/sql/scripts/mgblty_stop
sleep 10
$SQ_ROOT/sql/scripts/dcsstop
$SQ_ROOT/sq/scripts/dcsstart
sleep 5
$SQ_ROOT/sql/scripts/mgblty_start

$SQ_ROOT/dbmgr-2.1.0/bin/dbmgr.sh stop
$SQ_ROOT/dbmgr-2.1.0/bin/dbmgr.sh start



#echo \"initialize trafodion;\" | $SQ_ROOT/export/bin64/sqlci | tee -a $SQ_ROOT/initializeErrors.txt

#==========================================
