#!/bin/bash

# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

#  Setup Trafodion environment on a Cluster System

#==============================================

timestamp=$(date +%F-%H-%M-%S)
source /etc/trafodion/trafodion_config

cd $LOCAL_WORKDIR

echo "***Log File: trafodion_setup script***" >> $INSTALL_LOG
echo >> $INSTALL_LOG
echo "Username: $TRAF_USER" >> $INSTALL_LOG
echo "Nodes: $NODE_LIST" >> $INSTALL_LOG
echo "Home directory: $HOME_DIR" >> $INSTALL_LOG
echo >> $INSTALL_LOG

echo "***INFO: Starting Trafodion environment setup ($timestamp)"

#==============================================
# Set some limits needed by Trafodion

TRAF_LIMITS_CONF="$TRAF_WORKDIR/trafodion.conf"
sudo rm $TRAF_WORKDIR/trafodion.conf &>/dev/null

echo "***INFO: modifying limits in $TRAF_LIMITS_CONF on all nodes"

# append Trafodion settings to end of file
echo "# Trafodion settings" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   soft   core unlimited" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   hard   core unlimited" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   soft   memlock unlimited" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   hard   memlock unlimited" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   soft   nofile 32768" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   hard   nofile 65536" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   soft   nproc 100000" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   hard   nproc 100000" >> $TRAF_LIMITS_CONF
echo "hbase soft nofile 8192" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   soft nofile 8192" >> $TRAF_LIMITS_CONF
echo "$TRAF_USER   hard nofile 65535" >> $TRAF_LIMITS_CONF

sudo cp $TRAF_LIMITS_CONF /etc/security/limits.d/trafodion.conf
if [ $? != 0 ]; then
   echo "***ERROR: unable to copy $TRAF_LIMITS_CONF to /etc/security/limits.d/trafodion.conf"
   exit -1
fi

#=======================================
